---
version: '3'
services:
  control-center:
    image: confluentinc/cp-enterprise-control-center:6.2.4
    container_name: control-center
    networks:
    - kafka     
    depends_on:
      - zookeeper
      - broker1
      - broker2
      - schema-registry
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_LOG4J_ROOT_LOGLEVEL: DEBUG
      CONTROL_CENTER_LOG4J_LOGLEVEL: DEBUG
      CONTROL_CENTER_BOOTSTRAP_SERVERS: broker1.local:29093,broker2.local:29092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper.local:22181
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: SSL://schema-registry.local:8081
      CONTROL_CENTER_STREAMS_SECURITY_PROTOCOL: SSL
      CONTROL_CENTER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.control-center.truststore.jks
      CONTROL_CENTER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.control-center.keystore.jks
      CONTROL_CENTER_SSL_TRUSTSTORE_PASSWORD: kafkatest
      CONTROL_CENTER_SSL_KEYSTORE_PASSWORD: kafkatest
      CONTROL_CENTER_SSL_KEY_PASSWORD: kafkatest
      CONTROL_CENTER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      CONTROL_CENTER_STREAMS_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.control-center.truststore.jks
      CONTROL_CENTER_STREAMS_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.control-center.keystore.jks
      CONTROL_CENTER_STREAMS_SSL_TRUSTSTORE_PASSWORD: kafkatest
      CONTROL_CENTER_STREAMS_SSL_KEYSTORE_PASSWORD: kafkatest
      CONTROL_CENTER_STREAMS_SSL_KEY_PASSWORD: kafkatest
      CONTROL_CENTER_STREAMS_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      CONTROL_CENTER_OPTS: -Djavax.net.ssl.trustStore=/etc/kafka/secrets/kafka.control-center.truststore.jks
                  -Djavax.net.ssl.trustStorePassword=kafka
                  -Djavax.net.ssl.keyStore=/etc/kafka/secrets/kafka.control-center.keystore.jks
                  -Djavax.net.ssl.keyStorePassword=kafka
      PORT: 9021
    volumes:
      - ./secrets:/etc/kafka/secrets

  broker1:
    image: confluentinc/cp-enterprise-kafka:6.2.4
    container_name: broker1
    networks:
    - kafka
    hostname: broker1.local
    ports:
      - "29093:29093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper.local:22181
      KAFKA_ADVERTISED_LISTENERS: SSL://broker1.local:29093
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker.keystore.jks
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.broker.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: kafkatest
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker_keystore_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: kafkatest
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker_truststore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker_sslkey_creds
      KAFKA_SSL_KEYSTORE_TYPE: JKS
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_SECURITY_PROTOCOL: SSL
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./secrets:/etc/kafka/secrets

  schema-registry:
    image: confluentinc/cp-schema-registry:6.2.4
    depends_on:
      - zookeeper
      - broker1
    container_name: schema-registry
    hostname: schema-registry.local
    networks:
    - kafka
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker1.local:29093
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SSL
      SCHEMA_REGISTRY_HOST_NAME: schema-registry.local
      SCHEMA_REGISTRY_LISTENERS: SSL://0.0.0.0:8081
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: ""
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: DEBUG
      SCHEMA_REGISTRY_LOG4J_LOGLEVEL: DEBUG
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.schema-registry.truststore.jks
      SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.schema-registry.keystore.jks
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD: kafkatest
      SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD: kafkatest
      SCHEMA_REGISTRY_SSL_KEY_PASSWORD: kafkatest
      SCHEMA_REGISTRY_KAFKASTORE_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.schema-registry.truststore.jks
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.schema-registry.keystore.jks
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD: kafkatest
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_PASSWORD: kafkatest
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEY_PASSWORD: kafkatest
      SCHEMA_REGISTRY_SSL_CLIENT_AUTH: "true"
      SCHEMA_REGISTRY_DEBUG: true
    volumes:
      - ./secrets:/etc/kafka/secrets

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.4
    container_name: zookeeper
    networks:
    - kafka
    hostname: zookeeper.local
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: INFO
      ZOOKEEPER_LOG4J_LOGLEVEL: INFO

  broker2:
    image: confluentinc/cp-enterprise-kafka:6.2.4
    container_name: broker2
    networks:
    - kafka
    hostname: broker2.local
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper.local:22181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2.local:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - ./secrets:/etc/kafka/secrets

networks:
  kafka:
