//using Avro;
using Avro;
using Avro.Generic;
using Confluent.Kafka;
using Confluent.SchemaRegistry;
using Confluent.SchemaRegistry.Serdes;
using Frends.Kafka.Produce.Definitions;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Frends.Kafka.Produce;

/// <summary>
/// Kafka Task
/// </summary>
public class Kafka
{
    /// <summary>
    /// Kafka produce operation.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.Kafka.Produce)
    /// </summary>
    /// <param name="input">Input parameters.</param>
    /// <param name="options">Optional parameters.</param>
    /// <param name="socket">Socket parametes.</param>
    /// <param name="sasl">SASL parameters.</param>
    /// <param name="ssl">SSL parameters.</param>
    /// <param name="schemaRegistry">Schema registry parameters.</param>
    /// <param name="cancellationToken">Token generated by Frends to stop this Task.</param>
    /// <returns>Object { bool Success, string Status, string TopicPartitionOffset, string Timestamp }</returns>
    public static async Task<Result> Produce([PropertyTab] Input input, [PropertyTab] Options options, [PropertyTab] Socket socket, [PropertyTab] Sasl sasl, [PropertyTab] Ssl ssl, [PropertyTab] SchemaRegistry schemaRegistry, CancellationToken cancellationToken)
    {
        try
        {
            var producerConfig = GetProducerConfig(input, options, socket, sasl, ssl);
            if (schemaRegistry.UseSchemaRegistry)
                return await ProduceAvro(input.Topic, input.Key, schemaRegistry, producerConfig, cancellationToken);

            return await ProduceBasic(input.Topic, input.Partition, input.Key, input.Message, producerConfig, cancellationToken);
        }
        catch (KafkaException ke)
        {
            throw new Exception($"Produce KafkaException: {ke}");
        }
        catch (Exception ex)
        {
            throw new Exception($"Produce Exception: {ex}");
        }
    }

    private static async Task<Result> ProduceBasic(string topic, int partition, string msgKey, string msg, ProducerConfig producerConfig, CancellationToken cancellationToken)
    {
        using var producer = new ProducerBuilder<string, string>(producerConfig).Build();

        TopicPartition topicPartition;
        if (partition >= 0)
            topicPartition = new TopicPartition(topic, new Partition(partition));
        else
            topicPartition = new TopicPartition(topic, new Partition());

        Message<string, string> message = new()
        {
            Key = msgKey ?? null,
            Value = msg
        };

        var result = await producer.ProduceAsync(topicPartition, message, cancellationToken);
        return new Result(true, result.Status.ToString(), result.TopicPartitionOffset.ToString(), result.Timestamp.UtcDateTime.ToString());
    }

    private static async Task<Result> ProduceAvro(string topic, string msgKey, SchemaRegistry schemaRegistry, ProducerConfig producerConfig, CancellationToken cancellationToken)
    {
        try
        {
            var schemaRegistryConfig = new SchemaRegistryConfig()
            {
                Url = schemaRegistry.SchemaRegistryUrl,
                BasicAuthCredentialsSource = GetBasicAuthCredentialsSource(schemaRegistry.BasicAuthCredentialsSource),
                EnableSslCertificateVerification = schemaRegistry.EnableSslCertificateVerification,
                BasicAuthUserInfo = schemaRegistry.BasicAuthUserInfo,
                RequestTimeoutMs = schemaRegistry.RequestTimeoutMs,
                MaxCachedSchemas = schemaRegistry.MaxCachedSchemas,
            };

            if (!string.IsNullOrEmpty(schemaRegistry.SslCaLocation))
            {
                schemaRegistryConfig.SslCaLocation = schemaRegistry.SslCaLocation;
                schemaRegistryConfig.SslKeystorePassword = schemaRegistry.SslKeystorePassword;
                schemaRegistryConfig.SslKeystoreLocation = schemaRegistry.SslKeystoreLocation;
            }

            using var cachedSchemaRegistryClient = new CachedSchemaRegistryClient(schemaRegistryConfig);
            using var producer = new ProducerBuilder<string, GenericRecord>(producerConfig)
                .SetValueSerializer(new AvroSerializer<GenericRecord>(cachedSchemaRegistryClient))
                .Build();

            var avroSchema = (RecordSchema)Avro.Schema.Parse(!string.IsNullOrEmpty(schemaRegistry.RecordSchemaJsonFile)
                        ? File.ReadAllText(schemaRegistry.RecordSchemaJsonFile)
                        : schemaRegistry.RecordSchemaJson);

            JObject recordsJObject = JObject.Parse(schemaRegistry.Records);

            var records = new GenericRecord(avroSchema);
            AddFields(avroSchema, recordsJObject, records);

            var result = await producer.ProduceAsync(topic, new Message<string, GenericRecord> { Key = msgKey, Value = records }, cancellationToken);
            return new Result(true, result.Status.ToString(), result.TopicPartitionOffset.ToString(), result.Timestamp.UtcDateTime.ToString());
        }
        catch (ProduceException<string, GenericRecord> e)
        {
            var i = $"Failed to deliver message to {e.DeliveryResult.TopicPartitionOffset}. Error: {e.Error.Reason}";
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Unexpected error producing to Kafka: {ex.Message}");
        }

        return new Result(false, "Failed", null, null);
    }

    private static void AddFields(RecordSchema schema, JObject jObject, GenericRecord record)
    {
        foreach (var field in schema.Fields)
        {
            if (jObject.TryGetValue(field.Name, out JToken token))
            {
                // Field is present in JObject
                switch (field.Schema.Tag)
                {
                    case Avro.Schema.Type.Enumeration:
                        var enumSchema = (EnumSchema)field.Schema;
                        record.Add(field.Name, new GenericEnum(enumSchema, token.ToObject<string>()));
                        break;
                    case Avro.Schema.Type.Fixed:
                        var fixedSchema = (FixedSchema)field.Schema;
                        var bytes = Convert.FromBase64String(token.ToObject<string>());
                        record.Add(field.Name, new GenericFixed(fixedSchema, bytes));
                        break;
                    case Avro.Schema.Type.Array:
                        var array = token.ToObject<string[]>();
                        record.Add(field.Name, array);
                        break;
                    case Avro.Schema.Type.Null:
                        record.Add(field.Name, null);
                        break;
                    case Avro.Schema.Type.Boolean:
                        record.Add(field.Name, token.ToObject<bool>());
                        break;
                    case Avro.Schema.Type.Int:
                        record.Add(field.Name, token.ToObject<int>());
                        break;
                    case Avro.Schema.Type.Long:
                        record.Add(field.Name, token.ToObject<long>());
                        break;
                    case Avro.Schema.Type.Float:
                        record.Add(field.Name, token.ToObject<float>());
                        break;
                    case Avro.Schema.Type.Double:
                        record.Add(field.Name, token.ToObject<double>());
                        break;
                    case Avro.Schema.Type.Bytes:
                        record.Add(field.Name, Encoding.UTF8.GetBytes(token.ToObject<string>()));
                        break;
                    case Avro.Schema.Type.String:
                        record.Add(field.Name, token.ToObject<string>());
                        break;
                    case Avro.Schema.Type.Record:
                        var recordSchema = (RecordSchema)field.Schema;
                        var nestedRecord = new GenericRecord(recordSchema);
                        AddFields(recordSchema, (JObject)token, nestedRecord);
                        record.Add(field.Name, nestedRecord);
                        break;
                    case Avro.Schema.Type.Map:
                        var mapObject = token.ToObject<Dictionary<string, JToken>>();
                        var resultMap = new Dictionary<string, object>();
                        foreach (var kvp in mapObject)
                        {
                            resultMap[kvp.Key] = ConvertTokenToAvroType(kvp.Value, kvp.Value.Type);
                        }
                        record.Add(field.Name, resultMap);
                        break;
                    case Avro.Schema.Type.Union:
                        var unionSchema = (UnionSchema)field.Schema;
                        if (unionSchema.Schemas[1].Tag == Avro.Schema.Type.Null && token.Type == JTokenType.Null)
                        {
                            record.Add(field.Name, null);
                        }
                        else if (unionSchema.Schemas[1].Tag == Avro.Schema.Type.String && token.Type == JTokenType.String)
                        {
                            record.Add(field.Name, token.ToObject<string>());
                        }
                        // Add more cases as needed for other types in the union
                        else
                        {
                            throw new InvalidOperationException($"Unsupported union type: {unionSchema.Schemas[1].Tag}");
                        }
                        break;
                    case Avro.Schema.Type.Error:
                        throw new InvalidOperationException("Error type not supported");
                    case Avro.Schema.Type.Logical:
                        throw new InvalidOperationException("Logical type not supported");
                    default:
                        throw new InvalidOperationException($"Unsupported Avro type: {field.Schema.Tag}");
                }
            }
            else
            {
                // Field is not present in JObject
                if (field.Schema is UnionSchema unionSchema)
                {
                    // Field is optional
                    if (field.DefaultValue != null)
                    {
                        // Set field to default value
                        switch (unionSchema.Schemas[1].Tag)
                        {
                            case Avro.Schema.Type.Record:
                                var nestedRecord = new GenericRecord((RecordSchema)unionSchema.Schemas[1]);
                                AddFields((RecordSchema)unionSchema.Schemas[1], JObject.Parse(field.DefaultValue.ToString()), nestedRecord);
                                record.Add(field.Name, nestedRecord);
                                break;
                            default:
                                record.Add(field.Name, field.DefaultValue);
                                break;
                        }
                    }
                    else
                    {
                        // Set field to null
                        record.Add(field.Name, null);
                    }
                }
                else
                {
                    // Field is required but not present in JObject
                    throw new InvalidOperationException($"Missing required field: {field.Name}");
                }
            }
        }
    }

    private static object ConvertTokenToAvroType(JToken token, JTokenType type)
    {
        switch (type)
        {
            case JTokenType.Null:
                return null;
            case JTokenType.Boolean:
                return token.ToObject<bool>();
            case JTokenType.Integer:
                return token.ToObject<int>();
            case JTokenType.Float:
                return token.ToObject<double>();
            case JTokenType.String:
                return token.ToObject<string>();
            case JTokenType.Bytes:
                return Encoding.UTF8.GetBytes(token.ToObject<string>());
            default:
                throw new InvalidOperationException($"Unsupported token type: {type}");
        }
    }





    private static ProducerConfig GetProducerConfig(Input input, Options options, Socket socket, Sasl sasl, Ssl ssl)
    {
        ProducerConfig config = new()
        {
            Acks = GetAcks(options.Acks),
            ApiVersionRequest = options.ApiVersionRequest,
            BootstrapServers = input.Host,
            CompressionType = GetCompressionType(input.CompressionType),
            EnableIdempotence = options.EnableIdempotence,
            LingerMs = options.LingerMs,
            MaxInFlight = options.MaxInFlight,
            MessageTimeoutMs = options.MessageTimeoutMs,
            MessageMaxBytes = options.MessageMaxBytes,
            MessageSendMaxRetries = options.MessageSendMaxRetries,
            Partitioner = GetPartitioner(options.Partitioner),
            QueueBufferingMaxKbytes = options.QueueBufferingMaxKbytes,
            QueueBufferingMaxMessages = options.QueueBufferingMaxMessages,
            SecurityProtocol = GetSecurityProtocol(input.SecurityProtocol),
            SocketTimeoutMs = socket.SocketTimeoutMs,
            SocketConnectionSetupTimeoutMs = socket.SocketConnectionSetupTimeoutMs,
            SocketKeepaliveEnable = socket.SocketKeepaliveEnable,
            SocketMaxFails = socket.SocketMaxFails,
            SocketNagleDisable = socket.SocketNagleDisable,
            SocketReceiveBufferBytes = socket.SocketReceiveBufferBytes,
            TransactionalId = options.TransactionalId,
            TransactionTimeoutMs = options.TransactionTimeoutMs,
            Debug = "all",
        };

        if (sasl.UseSasl)
        {
            if (!RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
                throw new NotImplementedException("Sasl is implemented only on Linux OS.");
            config.SaslMechanism = GetSaslMechanism(sasl.SaslMechanism);
            config.SaslUsername = sasl.SaslUsername;
            config.SaslPassword = sasl.SaslPassword;
            config.SaslOauthbearerMethod = GetSaslOauthbearerMethod(sasl.SaslOauthbearerMethod);
            config.SaslOauthbearerClientId = string.IsNullOrEmpty(sasl.SaslOauthbearerClientId) ? null : sasl.SaslOauthbearerClientId;
            config.SaslOauthbearerClientSecret = string.IsNullOrEmpty(sasl.SaslOauthbearerClientSecret) ? null : sasl.SaslOauthbearerClientSecret;
            config.SaslOauthbearerTokenEndpointUrl = string.IsNullOrEmpty(sasl.SaslOauthbearerTokenEndpointUrl) ? null : sasl.SaslOauthbearerTokenEndpointUrl;
            config.SaslOauthbearerConfig = string.IsNullOrEmpty(sasl.SaslOauthbearerConfig) ? null : sasl.SaslOauthbearerConfig;
            config.SaslOauthbearerExtensions = string.IsNullOrEmpty(sasl.SaslOauthbearerExtensions) ? null : sasl.SaslOauthbearerExtensions;
            config.SaslOauthbearerScope = string.IsNullOrEmpty(sasl.SaslOauthbearerScope) ? null : sasl.SaslOauthbearerScope;
            config.SaslKerberosKeytab = string.IsNullOrEmpty(sasl.SaslKerberosKeytab) ? null : sasl.SaslKerberosKeytab;
            config.SaslKerberosMinTimeBeforeRelogin = sasl.SaslKerberosMinTimeBeforeRelogin;
            config.SaslKerberosPrincipal = sasl.SaslKerberosPrincipal;
            config.SaslKerberosServiceName = sasl.SaslKerberosServiceName;
        }

        if (ssl.UseSsl)
        {
            config.SslEndpointIdentificationAlgorithm = GetSslEndpointIdentificationAlgorithm(ssl.SslEndpointIdentificationAlgorithm);
            config.EnableSslCertificateVerification = ssl.EnableSslCertificateVerification;
            config.SslCertificateLocation = string.IsNullOrEmpty(ssl.SslCertificateLocation) ? null : ssl.SslCertificateLocation;
            config.SslCertificatePem = string.IsNullOrEmpty(ssl.SslCertificatePem) ? null : ssl.SslCertificatePem;
            config.SslCaCertificateStores = string.IsNullOrEmpty(ssl.SslCaCertificateStores) ? null : ssl.SslCaCertificateStores;
            config.SslCaLocation = string.IsNullOrEmpty(ssl.SslCaLocation) ? null : ssl.SslCaLocation;
            config.SslCaPem = string.IsNullOrEmpty(ssl.SslCaPem) ? null : ssl.SslCaPem;
            config.SslKeyLocation = string.IsNullOrEmpty(ssl.SslKeyLocation) ? null : ssl.SslKeyLocation;
            config.SslKeyPassword = string.IsNullOrEmpty(ssl.SslKeyPassword) ? null : ssl.SslKeyPassword;
            config.SslKeyPem = string.IsNullOrEmpty(ssl.SslKeyPem) ? null : ssl.SslKeyPem;
            config.SslKeystoreLocation = string.IsNullOrEmpty(ssl.SslKeystoreLocation) ? null : ssl.SslKeystoreLocation;
            config.SslKeystorePassword = string.IsNullOrEmpty(ssl.SslKeystorePassword) ? null : ssl.SslKeystorePassword;
            config.SslEngineLocation = string.IsNullOrEmpty(ssl.SslEngineLocation) ? null : ssl.SslEngineLocation;
            config.SslCipherSuites = string.IsNullOrEmpty(ssl.SslCipherSuites) ? null : ssl.SslCipherSuites;
            config.SslCrlLocation = string.IsNullOrEmpty(ssl.SslCrlLocation) ? null : ssl.SslCrlLocation;
            config.SslCurvesList = string.IsNullOrEmpty(ssl.SslCurvesList) ? null : ssl.SslCurvesList;
            config.SslSigalgsList = string.IsNullOrEmpty(ssl.SslSigalgsList) ? null : ssl.SslSigalgsList;
        }

        return config;
    }

    private static AuthCredentialsSource GetBasicAuthCredentialsSource(AuthCredentialsSources authCredentialsSources)
    {
        return authCredentialsSources switch
        {
            AuthCredentialsSources.UserInfo => AuthCredentialsSource.UserInfo,
            AuthCredentialsSources.SaslInherit => AuthCredentialsSource.SaslInherit,
            _ => throw new ArgumentException($"GetBasicAuthCredentialsSource exception: Value '{authCredentialsSources}' not supported."),
        };
    }

    private static SecurityProtocol GetSecurityProtocol(SecurityProtocols securityProtocols)
    {
        return securityProtocols switch
        {
            SecurityProtocols.Plaintext => SecurityProtocol.Plaintext,
            SecurityProtocols.Ssl => SecurityProtocol.Ssl,
            SecurityProtocols.SaslPlaintext => SecurityProtocol.SaslPlaintext,
            SecurityProtocols.SaslSsl => SecurityProtocol.SaslSsl,
            _ => throw new ArgumentException($"GetSecurityProtocol exception: Value '{securityProtocols}' not supported."),
        };
    }

    private static SslEndpointIdentificationAlgorithm GetSslEndpointIdentificationAlgorithm(SslEndpointIdentificationAlgorithms sslEndpointIdentificationAlgorithms)
    {
        return sslEndpointIdentificationAlgorithms switch
        {
            SslEndpointIdentificationAlgorithms.None => SslEndpointIdentificationAlgorithm.None,
            SslEndpointIdentificationAlgorithms.Https => SslEndpointIdentificationAlgorithm.Https,
            _ => throw new ArgumentException($"GetSslEndpointIdentificationAlgorithm exception: Value '{sslEndpointIdentificationAlgorithms}' not supported."),
        };
    }

    private static CompressionType GetCompressionType(CompressionTypes compressionType)
    {
        return compressionType switch
        {
            CompressionTypes.None => CompressionType.None,
            CompressionTypes.Gzip => CompressionType.Gzip,
            CompressionTypes.Snappy => CompressionType.Snappy,
            CompressionTypes.Lz4 => CompressionType.Lz4,
            CompressionTypes.Zstd => CompressionType.Zstd,
            _ => throw new ArgumentException($"GetCompressionType exception: Value '{compressionType}' not supported."),
        };
    }

    private static Acks GetAcks(Ack ack)
    {
        return ack switch
        {
            Ack.None => Acks.None,
            Ack.Leader => Acks.Leader,
            Ack.All => Acks.All,
            _ => throw new ArgumentException($"GetAcks exception: Value {ack} not supported."),
        };
    }

    private static Partitioner GetPartitioner(Partitioners partitioners)
    {
        return partitioners switch
        {
            Partitioners.Random => Partitioner.Random,
            Partitioners.Consistent => Partitioner.Consistent,
            Partitioners.ConsistentRandom => Partitioner.ConsistentRandom,
            Partitioners.Murmur2 => Partitioner.Murmur2,
            Partitioners.Murmur2Random => Partitioner.Murmur2Random,
            _ => throw new ArgumentException($"GetPartitioner exception: Value '{partitioners}' not supported."),
        };
    }

    private static SaslOauthbearerMethod GetSaslOauthbearerMethod(SaslOauthbearerMethods saslOauthbearerMethods)
    {
        return saslOauthbearerMethods switch
        {
            SaslOauthbearerMethods.Default => SaslOauthbearerMethod.Default,
            SaslOauthbearerMethods.Oidc => SaslOauthbearerMethod.Oidc,
            _ => throw new ArgumentException($"GetSaslOauthbearerMethod exception: Value '{saslOauthbearerMethods}' not supported."),
        };
    }

    private static SaslMechanism GetSaslMechanism(SaslMechanisms saslMechanisms)
    {
        return saslMechanisms switch
        {
            SaslMechanisms.Gssapi => SaslMechanism.Gssapi,
            SaslMechanisms.Plain => SaslMechanism.Plain,
            SaslMechanisms.ScramSha256 => SaslMechanism.ScramSha256,
            SaslMechanisms.ScramSha512 => SaslMechanism.ScramSha512,
            SaslMechanisms.OAuthBearer => SaslMechanism.OAuthBearer,
            _ => throw new ArgumentException($"GetSaslMechanism exception: Value '{saslMechanisms}' not supported."),
        };
    }
}