name: Consume build test

on:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.Kafka.Consume/**'
  workflow_dispatch:

jobs:
  linux_build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.Kafka.Consume
      env_var_name_1: ConfluentKafka_BootstrapServers
      env_var_name_2: ConfluentKafka_APIKey
      env_var_name_3: ConfluentKafka_APIKeySecret
      env_var_name_4: ConfluentKafka_SchemaRegistryURL
      env_var_name_5: ConfluentKafka_SchemaRegistryAPIKey
      env_var_name_6: ConfluentKafka_SchemaRegistryAPIKeySecret
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.ConfluentKafka_BootstrapServers }}
      env_var_value_2: ${{ secrets.ConfluentKafka_APIKey }}
      env_var_value_3: ${{ secrets.ConfluentKafka_APIKeySecret }}
      env_var_value_4: ${{ secrets.ConfluentKafka_SchemaRegistryURL }}
      env_var_value_5: ${{ secrets.ConfluentKafka_SchemaRegistryAPIKey }}
      env_var_value_6: ${{ secrets.ConfluentKafka_SchemaRegistryAPIKeySecret }}