name: Produce build main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.Kafka.Produce/**'
  workflow_dispatch:

jobs:
  linux_build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.Kafka.Produce
      prebuild_command: ./Frends.Kafka.Producer.Tests/Prebuild/prebuildCommand.sh
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
  windows_build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.Kafka.Produce
      prebuild_command: .\Frends.Kafka.Produce.Tests\Prebuild\prebuildCommand.ps1
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}