name: Produce build test

on:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.Kafka.Produce/**'
  workflow_dispatch:

jobs:
  linux_build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.Kafka.Produce
      prebuild_command: docker-compose -f ./Frends.Kafka.Produce.Tests/Files/docker-compose.yml up -d
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
  windows_build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.Kafka.Produce
      prebuild_command: docker-compose -f ./Frends.Kafka.Produce.Tests/Files/docker-compose.yml up -d
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}